
package org.digitalpassport.ui;

import java.util.ArrayList;
import org.digitalpassport.api.commands.cTransactionManagement;
import org.digitalpassport.deserialize.json.cResponse;
import org.digitalpassport.jdbc.cDatabaseHandler;

/**
 *
 * @author Philip M. Trenwith
 */
public class cHistoryFrame extends javax.swing.JFrame
{
  private cDatabaseHandler m_oDatabase = null;
  private cTransactionManagement m_oTransactionManagement = null;
  /**
   * Creates new form cHistoryFrame
   */
  public cHistoryFrame()
  {
    initComponents();
    m_oDatabase = cDatabaseHandler.instance();
    m_oTransactionManagement = new cTransactionManagement();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane7 = new javax.swing.JScrollPane();
    tblFileHistory = new javax.swing.JTable();
    lblFile = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    tblFileHistory.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {
        "Name", "From", "To", "Value", "Currency", "Kind", "Commission Percent", "Time", "Block", "Tx Hash", "Gas Used"
      }
    )
    {
      Class[] types = new Class []
      {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean []
      {
        false, false, false, false, false, false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex)
      {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex)
      {
        return canEdit [columnIndex];
      }
    });
    tblFileHistory.getTableHeader().setReorderingAllowed(false);
    jScrollPane7.setViewportView(tblFileHistory);

    lblFile.setText("File:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblFile)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane7;
  private javax.swing.JLabel lblFile;
  private javax.swing.JTable tblFileHistory;
  // End of variables declaration//GEN-END:variables

  public void setFile(String sFile)
  {
    lblFile.setText("File: " + sFile);
  }

  public void getHistoryOfFile(int iID)
  {
    new Thread(()-> 
    {
      ArrayList<String> lsTransactions = m_oDatabase.getTransactions();
      for (String sTransaction: lsTransactions)
      {
        cResponse oResponse = m_oTransactionManagement.getTransactionStatus(sTransaction);
      }
    }).start();
  }
}
