
package org.digitalpassport.ui.panels;

import javax.swing.JFileChooser;
import org.digitalpassport.cryptography.cHashing;
import org.digitalpassport.jdbc.cDatabaseHandler;
import org.digitalpassport.ui.cRegisterFrame;

/**
 *
 * @author Philip M. Trenwith
 */
public class cFileSharingPanel extends javax.swing.JPanel
{
  private cRegisterFrame m_oRegistrationFrame = null;
  private boolean m_bLogin = false;
  private String m_sUsername = "";
  
  /**
   * Creates new form cFileSharingPanel
   */
  public cFileSharingPanel()
  {
    initComponents();
    
    btnLogin.setActionCommand("login");
    m_oRegistrationFrame = new cRegisterFrame(this);
  }
  
  public void setUsername(String sUsername)
  {
    m_bLogin = true;
    m_sUsername = sUsername;
    txtUsername.setText(sUsername);
    setLogin();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    btnUploadFile = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblFiles = new javax.swing.JTable();
    btnLogin = new javax.swing.JButton();
    lblPassword = new javax.swing.JLabel();
    txtUsername = new javax.swing.JTextField();
    lblUsername = new javax.swing.JLabel();
    btnRegister = new javax.swing.JButton();
    txtPassword = new javax.swing.JPasswordField();

    btnUploadFile.setText("Upload");
    btnUploadFile.setEnabled(false);
    btnUploadFile.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnUploadFileActionPerformed(evt);
      }
    });

    tblFiles.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {
        "ID", "Filename", "Owner"
      }
    )
    {
      Class[] types = new Class []
      {
        java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean []
      {
        false, false, false
      };

      public Class getColumnClass(int columnIndex)
      {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex)
      {
        return canEdit [columnIndex];
      }
    });
    tblFiles.setEnabled(false);
    jScrollPane1.setViewportView(tblFiles);

    btnLogin.setText("Login");
    btnLogin.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnLoginActionPerformed(evt);
      }
    });

    lblPassword.setText("Password:");

    lblUsername.setText("Username:");

    btnRegister.setText("Register");
    btnRegister.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnRegisterActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnUploadFile)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(8, 8, 8)
            .addComponent(btnLogin)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnRegister)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLogin)
          .addComponent(lblPassword)
          .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblUsername)
          .addComponent(btnRegister)
          .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnUploadFile)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnUploadFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUploadFileActionPerformed
  {//GEN-HEADEREND:event_btnUploadFileActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    int result = fileChooser.showOpenDialog(tblFiles);
    if (result == JFileChooser.APPROVE_OPTION) 
    {
      
    }
  }//GEN-LAST:event_btnUploadFileActionPerformed

  private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegisterActionPerformed
  {//GEN-HEADEREND:event_btnRegisterActionPerformed
    m_oRegistrationFrame.setBounds(getX()+getWidth()/2, getY()+getHeight()/2, m_oRegistrationFrame.getWidth(), m_oRegistrationFrame.getHeight());
    m_oRegistrationFrame.setVisible(true);
  }//GEN-LAST:event_btnRegisterActionPerformed

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLoginActionPerformed
  {//GEN-HEADEREND:event_btnLoginActionPerformed
    if (btnLogin.getActionCommand().equals("login"))
    {
      m_sUsername = txtUsername.getText();
      char[] cPassword = txtPassword.getPassword();
      String sPasswordHash = cHashing.hash(cPassword);
      cDatabaseHandler oDatabase = cDatabaseHandler.instance();
      m_bLogin = oDatabase.login(m_sUsername, sPasswordHash);
      if (m_bLogin)
      {
        setLogin();
      }
    }
    else if (btnLogin.getActionCommand().equals("logout"))
    {
      m_bLogin = false;
      setLogin();
    }
  }//GEN-LAST:event_btnLoginActionPerformed

  private void setLogin()
  {
    if (m_bLogin)
    {
      btnLogin.setText("Logout");
      btnLogin.setActionCommand("logout");
    }
    else
    {
      btnLogin.setText("Login");
      btnLogin.setActionCommand("login");
    }
    
    lblPassword.setEnabled(!m_bLogin);
    txtPassword.setEnabled(!m_bLogin);
    lblUsername.setEnabled(!m_bLogin);
    txtUsername.setEnabled(!m_bLogin);
    btnRegister.setEnabled(!m_bLogin);
    tblFiles.setEnabled(m_bLogin);
    btnUploadFile.setEnabled(m_bLogin);
    
    loadFiles();
  }
  
  private void loadFiles()
  {
    new Thread(()->
    {
      cDatabaseHandler oDatabase = cDatabaseHandler.instance();
      oDatabase.getFilesForOwner(TOOL_TIP_TEXT_KEY);
    }).start();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLogin;
  private javax.swing.JButton btnRegister;
  private javax.swing.JButton btnUploadFile;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblUsername;
  private javax.swing.JTable tblFiles;
  private javax.swing.JPasswordField txtPassword;
  private javax.swing.JTextField txtUsername;
  // End of variables declaration//GEN-END:variables

}
